name: 'Terraform check'
description: 'Terraform validate'
runs:
  using: "composite"
  steps:
    - id: version
      run: |
        cd ./iac
        terraform version
        terraform validate
      shell: bash