name: 'Terraform check'
description: 'Terraform validate'
inputs:
  service:
    description: 'service name'
    required: true
  accname:
    description: 'account name'
    required: true
  environment:  
    description: 'environment'
    required: true
  region:  
    description: 'region'
    required: true
  mgmt_account_id:  
    description: 'mgmt account id'
    required: true
  app_version:
    description: 'application version'
    required: true

runs:
  using: "composite"
  steps:
    - id: version
      run: |
        cd ./iac
        terraform version
        make init 'ACCNAME=${{ inputs.accname }}' 'ENVNAME=${{ inputs.environment }}' 'REGION=${{ inputs.region }}'
        terraform validate
        export TF_VAR_region=${{ matrix.region }}
        export TF_VAR_service=${{ env.SERVICE }}
        export TF_VAR_environment=${{ matrix.environment }}
        export TF_VAR_image_ecr=${{ env.MGMT_ACCOUNT_ID }}.dkr.ecr.${{ matrix.region }}.amazonaws.com/${{ env.SERVICE }}:latest
        export TF_VAR_app_version=${{env.APP_VERSION}}
        make plan 'ACCNAME=${{ matrix.accname }}' 'ENVNAME=${{ matrix.environment }}' 'REGION=${{ matrix.region }}'        
      shell: bash