name: 'terraform-check'
description: 'Terraform validate'
runs:
  using: "composite"
  steps:
    - id: validate
      run: |
        cd ./iac
        terraform version
        terraform init -backend=false
        terraform validate
      shell: bash