name: 'terraform-check'
description: 'Terraform validate'
inputs:
  accname:
    description: 'account name'
    required: true
  environment:  
    description: 'environment'
    required: true
  region:  
    description: 'region'
    required: true

runs:
  using: "composite"
  steps:
    - id: validate
      run: |
        cd ./iac
        terraform version
        terraform init -backend=false
        terraform validate
      shell: bash