name: 'terraform-apply'
description: 'Terraform Plan/Apply'
inputs:
  service:
    description: 'service name'
    required: true
  accname:
    description: 'account name'
    required: true
  environment:  
    description: 'environment'
    required: true
  region:  
    description: 'region'
    required: true
  account_number:  
    description: 'account_number'
    required: true
  build_number:  
    description: 'build_number'
    required: true
runs:
  using: "composite"
  steps:
    - id: plan
      run: |
        cd ./iac
        make init 'ACCNAME=${{ inputs.accname }}' 'ENVNAME=${{ inputs.environment }}' 'REGION=${{ inputs.region }}'
        export TF_VAR_region=${{ inputs.region }}
        export TF_VAR_service=${{ inputs.service }}
        export TF_VAR_environment=${{ inputs.environment }}
        export TF_VAR_image_ecr=${{ inputs.account_number }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ inputs.service }}:latest
        make plan 'ACCNAME=${{ inputs.accname }}' 'ENVNAME=${{ inputs.environment }}' 'REGION=${{ inputs.region }}'
        make apply 'ACCNAME=${{ inputs.accname }}' 'ENVNAME=${{ inputs.environment }}' 'REGION=${{ inputs.region }}'
      shell: bash