name: 'build-image'
description: 'Build Image'
inputs:
  service:
    description: 'service name'
    required: true
  build_number:
    description: 'build_number'
    required: true
runs:
  using: "composite"
  steps:
    - id: build-image
      run: |
          docker build --target release -t release-${{ inputs.service }}-${{ inputs.build_number }} .
          echo "buil complete"
          docker save release-${{ inputs.service }}-${{ inputs.build_number }} > /tmp/release-${{ inputs.service }}-${{ inputs.build_number }}.tar
          echo "save image"
          docker image rmi release-${{ inputs.service }}-${{ inputs.build_number }}:latest
          echo "remove image"
      shell: bash
