name: 'clean-self-hosted'
description: 'Clean up self-hosted runners'
inputs:
  service:
    description: 'service name'
    required: true
  build_number:
    description: 'build_number'
    required: true
  ecr_registry:
    description: 'ecr_registry'
    required: true
runs:
  using: "composite"
  steps:
    - id: clean
      run: |
        docker image rmi release-${{ inputs.service }}-${{ inputs.build_number }}
        docker image rmi ${{ inputs.ecr_registry }}/${{ inputs.service }}:${{ inputs.build_number }}
        docker image rmi ${{ inputs.ecr_registry }}/${{ inputs.service }}:latest
        rm /tmp/release-${{ inputs.service}}-${{ inputs.build_number }}.tar
      shell: bash