name: 'clean-self-hosted'
description: 'Clean up self-hosted runners'
runs:
  using: "composite"
  steps:
    - id: clean
      run: |      
        docker container prune -f
        docker image prune -a -f
      shell: bash