name: 'publish-image'
description: 'Publish Image'
inputs:
  service:
    description: 'service name'
    required: true
  build_number:
    description: 'build_number'
    required: true
  image-tar:
    description: 'image tar'
    required: true
  ecr_registry:
    description: 'ecr_registry'
    required: true

runs:
  using: "composite"
  steps:
    - id: load
      run: |
          echo "load"
          docker load --input ${{ inputs.image-tar }}
          echo "tags"
          docker tag release-${{ inputs.service }}-${{ inputs.build_number }}:latest ${{ inputs.ecr_registry }}/${{ inputs.service }}:${{ inputs.build_number }}
          docker tag release-${{ inputs.service }}-${{ inputs.build_number }}:latest ${{ inputs.ecr_registry }}/${{ inputs.service }}:latest
          echo "push"
          docker push ${{ inputs.ecr_registry }}/${{ inputs.service }}:${{ inputs.build_number }}
          docker push ${{ inputs.ecr_registry }}/${{ inputs.service }}:latest
          echo "remove image"
          docker image rmi release-${{ inputs.service }}-${{ inputs.build_number }}:latest
          docker image rmi ${{ inputs.ecr_registry }}/${{ inputs.service }}:${{ inputs.build_number }}
      shell: bash
