name: 'GitConfig'
description: 'Configurate GIT'
inputs:
  private_key:  
    description: 'ssh private key'
    required: true
runs:
  using: "composite"
  steps:
    - id: ssh-key-config 
      run: ./script.sh
      shell: bash
