name: 'matrix'
description: 'Matrix environment'
inputs:
  environment_type:
    description: 'environment'
    required: true
runs:
  using: "composite"
  steps:
    - id: matrix
      run: |
        pwd
        branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
        matrix=$(jq --arg branchName "$branchName" 'map(. | select((.runOn==$branchName) or (.runOn=="always")) )' ${{ inputs.environment_type}}.json )
        echo ::set-output name=matrix::{\"include\":$(echo $matrix)}\"
      shell: bash
