name: 'matrix'
description: 'Matrix environment'
inputs:
  environment_type:
    description: 'environment'
    required: true
outputs:
  matrix:
    description: "matrix"
    value: ${{ steps.matrix-step.outputs.matrix }}
runs:
  using: "composite"
  steps:
    - id: matrix-step
      run: |
        branchName=$(echo '${{ github.ref }}' | sed 's,refs/heads/,,g')
        echo $branchName
        matrix=$(jq --arg branchName "$branchName" 'map(. | select((.runOn==$branchName) or (.runOn=="always")) )' ${{ github.action_path }}/${{ inputs.environment_type}}.json )
        echo ::set-output name=matrix::{\"include\":$(echo $matrix)}\"
      shell: bash
